
name: CI

on:
  push:
    branches: [ dev, main ]
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
#               python -m pip install -r requirements\requirements.txt --upgrade pip

      - name: Run tests
        run: |
        pwd
        python -m unittest discover -s aqua-exercise/tests


